# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddy',
            name='relationships',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='from_person',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='to_person',
        ),
        migrations.AddField(
            model_name='travel',
            name='travelers',
            field=models.ManyToManyField(related_name='traveler', to='buddy.Buddy'),
        ),
    ]
