# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationships',
            field=models.ManyToManyField(related_name='_user_relationships_+', through='friends.Friendships', to='friends.User'),
        ),
        migrations.AlterUniqueTogether(
            name='friendships',
            unique_together=set([]),
        ),
    ]
